{{- include "frigate-notify.validate" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frigate-notify.fullname" . }}-config
  labels:
    {{- include "frigate-notify.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
